name: CI/CD github actions

on:
  push:
    branches:
      - "main"
      - "master"

jobs:
  build:
    runs-on: ubtuntu-latest
    steps:
      - name: Push repo
        uses: actions/checkout@v3
      - name: Print hello
        run: echo "hello world"